services:
  postgres-db-2:
    image: postgres:15
    container_name: postgres-db-2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: virtualbank
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  transaction-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db-2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db-2:5432/virtualbank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

volumes:
  postgres-data:
