server:
  port: 8082
spring:
  application:
    name: account-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      order: log-topic


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/